#!/usr/bin/env ruby

require "secret_env"
require 'open3'
config, env = ARGV.shift(2)
SecretEnv.load(env: env, secrets_file: config)
stdin, stdoe, t = Open3.popen2e(*ARGV)
stdin.close
stdoe.each do |line|
  puts line
end
exit t.value.exitstatus
